---
name: Build
run-name: Build
on:
  workflow_dispatch:
  push:

jobs:
  Build:
    uses: https://github.com/james9001/james9001-workflows/.gitea/workflows/build.yaml@a8f39127d7d0eca4158843e6f1faad834e6f4c41
    with:
      image_registry_namespace: ${{ secrets.FMA_IMAGE_REGISTRY_NAMESPACE }}
      image_registry_username: ${{ secrets.FMA_IMAGE_REGISTRY_USERNAME }}
    secrets:
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.FMA_IMAGE_REGISTRY_PASSWORD }}
